services:
  contoso-backend:
    build:
      context: .
      dockerfile: Dockerfile.java
    container_name: contoso-backend
    ports:
      - "5050:8080"
    volumes:
      - ./java/socialapp/sns_api.db:/app/sns_api.db
    networks:
      - contoso

  contoso-frontend:
    build:
      context: .
      dockerfile: Dockerfile.dotnet
    container_name: contoso-frontend
    ports:
      - "3030:8080"
    depends_on:
      - contoso-backend
    environment:
      - ApiBaseUrl=http://contoso-backend:8080
    networks:
      - contoso

networks:
  contoso:
    name: contoso
