services:
  contoso-backend:
    build:
      context: .
      dockerfile: Dockerfile.java
    container_name: contoso-backend
    ports:
      - "8080:8080"
    environment:
      - CODESPACE_NAME=${CODESPACE_NAME}
      - GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN=${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}
    volumes:
      - ./java/socialapp/sns_api.db:/app/sns_api.db
    networks:
      - contoso

  contoso-frontend:
    build:
      context: .
      dockerfile: Dockerfile.dotnet
    container_name: contoso-frontend
    ports:
      - "3030:8080"
    depends_on:
      - contoso-backend
    environment:
      - ApiSettings__BaseUrl=http://contoso-backend:8080/api/
    networks:
      - contoso

networks:
  contoso:
    name: contoso
